# Generated by Django 2.2.4 on 2021-01-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_dash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
