# Generated by Django 2.2.4 on 2021-01-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv_app', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
