# Generated by Django 2.2.4 on 2021-01-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy_shell', '0002_auto_20210112_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.TextField(max_length=45),
        ),
    ]
